spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/bootseller?characterEncoding-utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
      default-property-inclusion: non_null
#  redis:
#    host: 192.168.30.113
#    port: 6379
  redis:
      host: 180.97.69.171
      port: 6379
      password: jhonrain

server:
  context-path: /

wechat:
  mpAppId: wxbc12b25a14f84de6
  mpAppSecret: 3cb6f2aab41036f8fef367c7b938ad41

  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://jhonrainwx1321.tunnel.echomod.cn/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://jhonrainwx1321.tunnel.echomod.cn
  wechatOpenAuthorize: http://jhonrainwx1321.tunnel.echomod.cn
  sell: http://jhonrainwx1321.tunnel.echomod.cn